version:"3.3"
services :
  market-api:
    build:
      command: flask run --host 0.0.0.0
      ports :
        - 7000:5000
      volumes:
        - .:/python-flask
      enviroment:
        - "FLASK_APP=app.py"
      env_file:
        - .env
        